### ISSUE TITLE
support register services through glob expressions.

### ISSUE THREAD

**Issue by thiagobustamante** [thiagobustamante/typescript-rest#24]
Create a support to register services automatically, avoiding the annoying task to register each service, as previously describe in #21, or in #9.

The approach would be:

```typescript
  Server.loadServices(app, 'lib/controllers/*');
```

or 

```typescript
  Server.loadServices(app, ['lib/controllers/*', '!**/exclude*']); 
  // includes all controllers, excluding that one which name starts with 'exclude'
```

or 
```typescript
  Server.loadServices(app, 'controllers/*', `${__dirname}/..`]); 
  // Inform a folder as origin for the patterns
```

**Comment by vrudikov** [comment]
@thiagobustamante Could you explain why you named method "loadServices"? So we have controllers right now. What are other types of "services" exists?

**Comment by thiagobustamante** [comment]
I just used 'services' because we already have a method called ```Server.buildServices()``` that receives the annotated classes directly... I thought it would be more orthogonal.

```typescript
Server.buildServices(app, MyRestService, MyRestService2);
// or
Server.loadServices(app, 'controllers/*');
```

But I think we can have  an alias... I understand that a lot of people should prefer 'controller'... What do you think if we create this alias?

```typescript
Server.loadControllers(app, 'controllers/*');
```

**Comment by vrudikov** [comment]
Yeah, "loadControllers" is good and it comes from MVC pattern. And another point of view is - this project depends on "express" framework i think we could use the same naming convention as it described in [official documentation](http://expressjs.com/en/starter/basic-routing.html). I see that word 'HANDLER' is what describes the thing we annotate with @Path decorator. We also can use "loadHandlers" or "loadRestHandlers" too. But anyway i think you decision is more preferable. And i understand why you choosed "loadServices" because those classes are "serve" REST requests. No problemo. Just wanted to know the truth :call_me_hand:
