### ISSUE TITLE
Is there any annotation for authorize or has a way to custom annotation?

### ISSUE THREAD

**Issue by vellengs** [thiagobustamante/typescript-rest#36]
Is there any annotation for authorize or has a way to custom annotation?

**Comment by Johnz86** [comment]
There is no Authorize annotation, for which you can add your login handler like in Java JSR.
The best answer to get authorization to work is this:

https://github.com/thiagobustamante/typescript-rest/issues/23

I do not like it, because you need to register authenticated routes with midlleware. It would be nicer, if we could use annotation for path with list of roles as parameter. Similar to @RolesAllowed and @Secured in Java.

**Comment by ngraef** [comment]
Check out the new [`@Preprocessor` feature](https://github.com/thiagobustamante/typescript-rest#preprocessors) as another way to implement this.

**Comment by creadicted** [comment]
I used header parameter: 
`@HeaderParam('Authorization') token: string;`
and used that data in every controller i required a authentication 
```
public async getById(@PathParam('id') id: number): Promise<ReturnType> {
        const requestUser: User = await verifyToken(this.token);
        return new Promise<any>(async function (resolve, reject) {
            if (!requestUser) {
                throw new Errors.BadRequestError('The request was not valid');
            } 
```

It is not the nicest way but it also gives me the user that made the request to make additional validations further down the line. 
Not sure if the @Preprocessor also allows the return of a value.
